#!/bin/bash
# Author: Ikram Damri
# Description: This script will ping remote hosts & notify

### The code below will ping an address read by the user entry ###
# echo Enter a host ip address:
# read host
# ping -c1 $host &> /dev/null
#	if [ $? -eq 0 ]
#	then
#	    echo $host is OK!
#	else
#	    echo $host is Not OK!
#	fi


### The code below will ping addresses picked from a file ###
hosts='/home/ikram/hosts'


for ip in $(cat $hosts)

do
	ping -c1 $ip &> /dev/null
	      if [ $? -eq 0 ]
	      then
		     echo $ip ping passed
	      else
		     echo $ip ping failed
	      fi
done
