#!/bin/bash
# Author: ikram Damri
# Description: This script will pull only warning messages that are copied from /var/log/messages to the home directory:

grep -i warn /home/ikram/professional-scripts/messages.log
