#!/bin/bash
# Author: ikram Damri
# Description: This script will pull only Error messages that are copied from /var/log/messages to the home directory:

grep -i error /home/ikram/professional-scripts/messages.log
